# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'KSDetectionPlatform' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KSDetectionPlatform
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'SnapKit', '~> 3.2.0'
    pod 'Alamofire', '~> 4.4.0'
    pod 'SwiftyJSON', '~> 3.1.4'
    pod 'HandyJSON', '~> 1.6.0'
    pod 'SDCycleScrollView','1.64'

  target 'KSDetectionPlatformTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KSDetectionPlatformUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
